package live

const (
	inlineKeyboardTimes             = "Tiempos"
	inlineKeyboardBestLap           = "Mejor Vuelta"
	inlineKeyboardBestLapSectors    = "Sectores MV."
	inlineKeyboardLastLap           = "Última Vuelta"
	inlineKeyboardLastLapSectors    = "Sectores UV."
	inlineKeyboardOptimumLap        = "Óptimo"
	inlineKeyboardOptimumLapSectors = "Sectores O."
	inlineKeyboardSectors           = "Sectores"
	inlineKeyboardLiveMap           = "Map 🗺️"
	inlineKeyboardStatus            = "Estado 🏎️"
	inlineKeyboardInfo              = "Info 👐"
	inlineKeyboardDiff              = "Gap ⏳"
	inlineKeyboardCompound          = "Gomas"
	inlineKeyboardLaps              = "Vueltas"
	inlineKeyboardTeam              = "Coches"
	inlineKeyboardDriver            = "Pilotos"
	inlineKeyboardUpdate            = "Actualizar"
	inlineKeyboardMaxSpeed          = "Máx. Vel"
	inlineKeyboardCar               = "Coche"

	symbolTimes    = "⏱"
	symbolSectors  = "🔂"
	symbolCompound = "🛞"
	symbolLaps     = "🏁"
	symbolTeam     = "🏎️"
	symbolDriver   = "👐"
	symbolUpdate   = "🔄"
	symbolDiff     = "⏲️"
	symbolOptimum  = "🚀"
	symbolPhoto    = "📸"
)
